import Head from 'next/head'
import { MoveCard } from '@/components/Springs/index'
import Card from '@/components/Card'
import {
  MainStyle,
  ProfileImageStyle,
  NameStyle,
  ProfileStyle,
  MoveCardStyle,
  CardWrapperStyle,
  TitleStyle,
  TableStyle,
  UlStyle,
  TwitterIconStyle,
  GithubIconStyle,
  InstagramIconStyle,
  SnsStyle,
  AnchorStyle,
} from '@/pages/indexStyle'
import Link from 'next/link'
import { githubUrl, twitterUrl, instagramUrl } from '@/constants/url'

export default function Home() {
  return (
    <>
      <Head>
        <title>Shu Hirouchi - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainStyle>
        <MoveCardStyle>
          <MoveCard>
            <ProfileImageStyle
              src="/profile.JPG"
              width={160}
              height={160}
              alt="プロフィール画像"
            />
            <NameStyle>SHU HIROUCHI</NameStyle>
            <ProfileStyle>front-end engineer</ProfileStyle>
          </MoveCard>
        </MoveCardStyle>
        <CardWrapperStyle>
          <Card>
            <TitleStyle>Bio</TitleStyle>
            <TableStyle>
              <tbody>
                <tr>
                  <th>2002</th>
                  <td>埼玉県生まれ</td>
                </tr>
                <tr>
                  <th>2021</th>
                  <td>高等学校 卒業</td>
                </tr>
                <tr>
                  <th>2021</th>
                  <td>都内のWEB開発会社に入社</td>
                </tr>
              </tbody>
            </TableStyle>
          </Card>
          <Card>
            <TitleStyle>Stack</TitleStyle>
            <UlStyle>
              <li>JavaScript・Typescript</li>
              <li>React・Next.js</li>
              <li>Vue.js</li>
              <li>Three.js</li>
            </UlStyle>
          </Card>
          <Card>
            <TitleStyle>Other</TitleStyle>
            <UlStyle>
              <li>
                <Link href={githubUrl} passHref legacyBehavior>
                  <AnchorStyle>
                    <GithubIconStyle />
                    <SnsStyle>github</SnsStyle>
                  </AnchorStyle>
                </Link>
              </li>
              <li>
                <Link href={twitterUrl} passHref legacyBehavior>
                  <AnchorStyle>
                    <TwitterIconStyle />
                    <SnsStyle>twitter</SnsStyle>
                  </AnchorStyle>
                </Link>
              </li>
              <li>
                <Link href={instagramUrl} passHref legacyBehavior>
                  <AnchorStyle>
                    <InstagramIconStyle />
                    <SnsStyle>instagram</SnsStyle>
                  </AnchorStyle>
                </Link>
              </li>
            </UlStyle>
          </Card>
        </CardWrapperStyle>
      </MainStyle>
    </>
  )
}
