import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
  const Emoji = styled.main`
    font-family: 'Noto Color Emoji', sans-serif;
  `
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Emoji>👀</Emoji>
      </main>
    </>
  )
}
