import Head from 'next/head'
import { MainStyle } from '@/pages/workStyle'
import Masonry from '@/components/Springs/Masonry'
import Link from 'next/link'

export default function Work() {
  return (
    <>
      <Head>
        <title>Shu Hirouchi - Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainStyle>
        <Masonry />
      </MainStyle>
    </>
  )
}
